name: docker

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main

env:
  DOCKER_FRONTEND_REPO: osmolabs/faucet-frontend
  DOCKER_BACKEND_REPO: osmolabs/faucet-backend

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get commmit short sha
        run: echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV 
      - 
        name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          file: frontend/Dockerfile
          context: frontend/
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_FRONTEND_REPO }}:${{ env.SHORT_SHA }},${{ env.DOCKER_FRONTEND_REPO }}:main,${{ env.DOCKER_FRONTEND_REPO }}:latest
      - 
        name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          file: backend/Dockerfile
          context: backend/
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_BACKEND_REPO }}:${{ env.SHORT_SHA }},${{ env.DOCKER_BACKEND_REPO }}:main,${{ env.DOCKER_BACKEND_REPO }}:latest
